# =========================
# NOME DA APLICAÇÃO
# =========================
spring.application.name=cart_service
# Identifica o nome do microserviço no Spring Boot
# Usado em logs e monitoramento

# =========================
# PORTA DO SERVIDOR
# =========================
server.port=8081
# Define em qual porta a API vai rodar
# Ex: http://localhost:8081

# =========================
# MONGODB
# =========================
spring.data.mongodb.uri=mongodb://localhost:27017/cartdb
# Conexão com o MongoDB local
# localhost = máquina local
# 27017 = porta padrão do MongoDB
# cartdb = nome do banco de dados

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# =========================
# KAFKA - CONEXÃO
# =========================
spring.kafka.bootstrap-servers=localhost:9092
# Endereço do Kafka (broker)
# 9092 = porta padrão do Kafka

# =========================
# PRODUCER (ENVIO DE MENSAGENS)
# =========================

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
# Serializa a CHAVE da mensagem como String

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# Serializa o VALOR da mensagem como JSON
# Permite enviar objetos Java (ex: Cart)

# =========================
# CONSUMER (RECEBIMENTO DE MENSAGENS)
# =========================

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# Converte a chave recebida do Kafka para String

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
# Converte JSON recebido do Kafka em objeto Java

spring.kafka.consumer.properties.spring.json.trusted.packages=com.web.cart_service.model
# Define quais pacotes podem ser desserializados
# Segurança: evita execução de classes não autorizadas

spring.kafka.consumer.properties.spring.json.use.type.headers=false
# Desativa uso de headers de tipo do Kafka
# Evita conflitos de compatibilidade em alguns cenários

spring.kafka.consumer.group-id=cart-group
# Define o grupo de consumidores Kafka
# Consumidores com mesmo group-id dividem mensagens

spring.kafka.consumer.auto-offset-reset=earliest
# Define de onde começar a leitura:
# earliest = desde o início do tópico
# latest = apenas mensagens novas